### ISSUE TITLE
缺少很多模块

### ISSUE THREAD

**Issue by bangxingni** [lyj5812/yun-admin-ui#1]
permission.js?31c2:20 Cannot find module './views/admin/user/index'
permission.js?31c2:20 Cannot find module './views/admin/menu2/index'
permission.js?31c2:20 Cannot find module './views/admin/role/index'
permission.js?31c2:20 Cannot find module './views/admin/menu/index'
permission.js?31c2:20 Cannot find module './views/admin/dept/index'
permission.js?31c2:20 Cannot find module './views/admin/post/index'
permission.js?31c2:20 Cannot find module './views/permission/page'

**Comment by lyj5812** [comment]
这个是数据问题。
